export const TOKEN_MAP={"#":29,"%":30,")":31,"(":1,"+":32,"-":33,"/":34,".":2,"1":35,"0":3,"3":36,"2":4,"5":37,"4":5,"7":38,"6":6,"9":39,"8":7,"=":40,"A":41,"@":8,"C":42,"B":9,"E":43,"D":10,"G":44,"F":11,"I":45,"H":12,"K":46,"M":47,"L":13,"O":48,"N":14,"P":15,"S":49,"R":16,"U":50,"T":17,"W":51,"V":18,"Y":52,"[":53,"Z":19,"]":54,"\\":20,"a":55,"c":56,"b":21,"e":57,"d":22,"g":58,"f":23,"i":59,"h":24,"m":60,"l":25,"o":61,"n":26,"s":62,"r":27,"u":63,"t":28,"y":64};
export function tokens(smiles){if(!smiles||smiles.length>100)throw new Error('Fusion accepts 1–100 SMILES characters; inputs are never truncated.');const out=new BigInt64Array(100);Array.from(smiles).forEach((ch,i)=>{if(!TOKEN_MAP[ch])throw new Error('Unsupported SMILES token: '+ch);out[i]=BigInt(TOKEN_MAP[ch]);});return out;}
export const fusionChannels=['H','C.sp','C.sp2','C.sp3','N.sp','N.sp2','N.sp3','O','P','S.sp2','S.sp3','Se','halogen','other'];
export function fusionChannel(a){if(a.z===6||a.z===7){if(![1,2,3].includes(a.hyb))throw new Error('Unsupported carbon/nitrogen hybridization');return (a.z===6?1:4)+a.hyb-1;}if(a.z===16){if(![2,3].includes(a.hyb))throw new Error('Unsupported sulfur hybridization');return 9+a.hyb-2;}const map={1:0,8:7,15:8,34:11,9:12,17:12,35:12,53:12};if(a.z in map)return map[a.z];if([3,4,5,11,12,13,14].includes(a.z)||(a.z>=19&&a.z<=31)||(a.z>=37&&a.z<=50)||(a.z>=55&&a.z<=83))return 13;throw new Error('Element outside fusion atom typing');}
// Native typing precedes culling; FP32 endpoint distances preserve the 19.5 cutoff at adjacent floats.
export function fusionGrid(atoms){const data=new Float32Array(28*24**3),coords=atoms.map(a=>a.xyz.map(Math.fround)),atomChannels=atoms.map(fusionChannel);const center=[0,1,2].map(i=>Math.fround(Math.fround(Math.max(...coords.map(c=>c[i]))+Math.min(...coords.map(c=>c[i])))/2));let included=0;for(let i=0;i<atoms.length;i++){const p=coords[i].map((x,j)=>Math.fround(x-center[j]));if(p.some(v=>Math.max(Math.abs(Math.fround(v+9.5)),Math.abs(Math.fround(v-9.5)))>19.5))continue;const indices=p.map(v=>{let best=Infinity,index=0;for(let j=0;j<20;j++){const d=Math.abs(Math.fround(v-Math.fround(j-9.5)));if(d<best){best=d;index=j;}}return index;});const [x,y,z]=indices;data[(((14+atomChannels[i])*24+x)*24+y)*24+z]++;included++;}return {data,shape:[1,28,24,24,24],center,channels:['protein','ligand'].flatMap(prefix=>fusionChannels.map(c=>prefix+':'+c)),included,version:'fusion-grid-source-v1'};}
const subtract=(a,b)=>a.map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((v,x,i)=>v+x*b[i],0),norm=a=>Math.sqrt(dot(a,a)),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
export function angle(a,b,c){const v=subtract(a,b),w=subtract(c,b),nv=norm(v),nw=norm(w);return nv<1e-12||nw<1e-12?0:Math.acos(Math.max(-1,Math.min(1,dot(v,w)/(nv*nw))))*180/Math.PI;}
// This follows UniMolRep's p1-p0 first vector, including its dihedral convention.
export function torsion(p0,p1,p2,p3){const b0=subtract(p1,p0),b1=subtract(p2,p1),b2=subtract(p3,p2),n=norm(b1);if(n<1e-12)return 0;const u=b1.map(x=>x/n),v=subtract(b0,u.map(x=>x*dot(b0,u))),w=subtract(b2,u.map(x=>x*dot(b2,u)));if(norm(v)<1e-12||norm(w)<1e-12)return 0;return Math.atan2(dot(cross(u,v),w),dot(v,w))*180/Math.PI;}
export function binAngle(value,bins){return value>0?bins.findIndex(b=>value<=b)+1:0;}
export function geometricFeatures(atoms,bonds){const adj=atoms.map(()=>[]),edges=[];for(const b of bonds){adj[b.a].push(b.b);adj[b.b].push(b.a);edges.push([b.a,b.b],[b.b,b.a]);}const angles=[],torsions=[];for(const [i,s] of edges)for(const j of adj[s])if(j!==i){const degrees=angle(atoms[i].xyz,atoms[s].xyz,atoms[j].xyz),bin=binAngle(degrees,[60,120,150,180,360]);if(bin)angles.push({indices:[i,s,j],degrees,bin});}for(const b of bonds){const s=Math.min(b.a,b.b),j=Math.max(b.a,b.b);for(const i of adj[s])for(const t of adj[j])if(i!==j&&t!==s&&i!==t){const degrees=torsion(atoms[i].xyz,atoms[s].xyz,atoms[j].xyz,atoms[t].xyz),bin=binAngle(Math.abs(degrees),[60,120,150,180]);if(bin)torsions.push({indices:[i,s,j,t],degrees,bin});}}return {edges,angles,torsions};}
export const uniChannels=['C','N','O','S','P','F','Cl','Br','I','H','Met'];
export function representationGrid(atoms){const n=48,spacing=.5,sigma=.5,data=new Float32Array(22*n**3),center=[0,1,2].map(i=>Math.fround(atoms.reduce((s,a)=>s+a.xyz[i],0)/atoms.length)),origin=center.map(x=>Math.fround(x-12));for(const atom of atoms){const p=atom.xyz.map(Math.fround);if(p.some((v,i)=>v<origin[i]||v>origin[i]+24))continue;const index=uniChannels.indexOf(atom.symbol),channel=11+(index<0?10:index);const indices=p.map((v,i)=>Array.from({length:n},(_,j)=>j).filter(j=>Math.abs(Math.fround(origin[i]+(j+.5)*spacing)-v)<=3*sigma));for(const x of indices[0])for(const y of indices[1])for(const z of indices[2]){const g=[x,y,z].map((j,i)=>{const delta=Math.fround(Math.fround(origin[i]+(j+.5)*spacing)-p[i]);return Math.fround(Math.exp(Math.fround(-.5*Math.fround(Math.fround(delta/sigma)**2))));});const k=(((channel*n+x)*n+y)*n+z);data[k]=Math.fround(data[k]+Math.fround(Math.fround(g[0]*g[1])*g[2]));}}return {data,shape:[1,22,n,n,n],center,origin,channels:['protein','ligand'].flatMap(p=>uniChannels.map(c=>p+':'+c)),version:'unimolrep-grid-v1-explicit-center-no-rotation',spacing};}
