import test from 'node:test';
import assert from 'node:assert/strict';
import {ResearchArtifact,validateTensor,validateResult} from '../src/lib/research/contracts.mjs';
import {tokens,fusionGrid,angle,torsion} from '../src/lib/research/geometry.mjs';
import {verifiedArtifact} from '../src/lib/research/artifacts.mjs';
import {createHash} from 'node:crypto';
test('only immutable approved artifact locations pass',()=>{const a={path:'research/model.onnx',bytes:4,sha256:'a'.repeat(64)};assert.equal(ResearchArtifact.safeParse(a).success,true);for(const path of ['../x','/x','research/../../x','https://bad/x'])assert.equal(ResearchArtifact.safeParse({...a,path}).success,false);assert.equal(ResearchArtifact.safeParse({...a,path:undefined,url:'https://huggingface.co/a/b/resolve/main/model'}).success,false);assert.equal(ResearchArtifact.safeParse({...a,path:undefined,url:'https://huggingface.co/a/b/resolve/'+ 'a'.repeat(40)+'/model'}).success,true);});
test('integer tokens cannot truncate or silently map unsupported characters',()=>{assert.equal(tokens('CCO')[0],42n);assert.equal(tokens('CCO')[2],48n);assert.equal(tokens('CCO').length,100);assert.throws(()=>tokens('C'.repeat(101)));assert.throws(()=>tokens('C?'));});
test('fusion preserves ligand offset, zero protein channels and unusual 20-of-24 indexing',()=>{const g=fusionGrid([{z:6,hyb:3,xyz:[0,0,0]}]);assert.equal(g.data.reduce((a,b)=>a+b),1);assert.equal(g.data[((17*24+9)*24+9)*24+9],1);assert.equal(g.data.slice(0,14*24**3).some(Boolean),false);});
test('geometry handles right angles, signed torsions and degeneracy',()=>{assert.equal(angle([1,0,0],[0,0,0],[0,1,0]),90);assert.equal(Math.abs(torsion([0,0,0],[1,0,0],[1,1,0],[1,1,1])),90);assert.equal(angle([0,0,0],[0,0,0],[1,0,0]),0);});
test('runtime-neutral tensors require exact dtype, shape and finite data',()=>{const s={name:'grid',dtype:'float32',shape:[1,1,1,1,2]},t={...s,data:new Float32Array([1,2])};assert.equal(validateTensor(s,t),t);assert.throws(()=>validateTensor(s,{...t,data:new Int32Array([1,2])}));assert.throws(()=>validateTensor(s,{...t,data:new Float32Array([NaN,2])}));assert.throws(()=>validateResult({kind:'prediction',execution:'precomputed',outputs:[{name:'affinity',value:1}]}));});
test('downloads reject corruption, short responses and allow denied cache storage',async()=>{const original=globalThis.fetch,oldCache=globalThis.caches,bytes=new Uint8Array([1,2,3,4]);const a={path:'model',bytes:4,sha256:createHash('sha256').update(bytes).digest('hex')};globalThis.caches={open:async()=>{throw Error('denied')}};try{globalThis.fetch=async()=>new Response(bytes);assert.deepEqual(await verifiedArtifact(a,{base:'https://local.test/'}),bytes);globalThis.fetch=async()=>new Response(new Uint8Array([1,2]));await assert.rejects(verifiedArtifact(a,{base:'https://local.test/'}),/Incomplete/);globalThis.fetch=async()=>new Response(new Uint8Array([1,2,3,5]));await assert.rejects(verifiedArtifact(a,{base:'https://local.test/'}),/SHA-256/);}finally{globalThis.fetch=original;globalThis.caches=oldCache;}});
test('corrupt cache is evicted, verified replacement works offline, cancellation propagates',async()=>{const original=globalThis.fetch,oldCache=globalThis.caches,bytes=new Uint8Array([7,8]),a={path:'m',bytes:2,sha256:createHash('sha256').update(bytes).digest('hex')};let stored=new Response(new Uint8Array([0,0])),deleted=false;globalThis.caches={open:async()=>({match:async()=>stored?.clone(),delete:async()=>{deleted=true;stored=undefined;},put:async(_,r)=>{stored=r;}})};try{globalThis.fetch=async()=>new Response(bytes);await verifiedArtifact(a,{base:'https://local.test/'});assert.equal(deleted,true);globalThis.fetch=async()=>{throw Error('offline')};assert.deepEqual(await verifiedArtifact(a,{base:'https://local.test/'}),bytes);const c=new AbortController();c.abort();await assert.rejects(verifiedArtifact(a,{base:'https://local.test/',signal:c.signal}),/abort/i);}finally{globalThis.fetch=original;globalThis.caches=oldCache;}});

test('large verified artifacts cache in bounded pieces and recover from missing pieces',async()=>{const original=globalThis.fetch,oldCache=globalThis.caches,bytes=new Uint8Array(33*1024*1024);bytes[0]=9;bytes[bytes.length-1]=7;const a={path:'large.bin',bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')},stored=new Map();let downloads=0;globalThis.caches={open:async()=>({match:async key=>stored.get(key)?.clone(),delete:async key=>stored.delete(key),put:async(key,response)=>{assert.ok(Number(response.headers.get('content-length'))<=32*1024*1024);stored.set(key,response);}})};try{globalThis.fetch=async()=>{downloads++;return new Response(bytes)};assert.deepEqual(await verifiedArtifact(a,{base:'https://local.test/'}),bytes);assert.equal(stored.size,2);const control=new AbortController();control.abort();await assert.rejects(verifiedArtifact(a,{base:'https://local.test/',signal:control.signal}),/abort/i);assert.equal(stored.size,2);globalThis.fetch=async()=>{throw Error('offline')};assert.deepEqual(await verifiedArtifact(a,{base:'https://local.test/'}),bytes);stored.delete([...stored.keys()][1]);globalThis.fetch=async()=>{downloads++;return new Response(bytes)};assert.deepEqual(await verifiedArtifact(a,{base:'https://local.test/'}),bytes);assert.equal(downloads,2);assert.equal(stored.size,2);}finally{globalThis.fetch=original;globalThis.caches=oldCache;}});
