import {occlusionDisplay,regionLabel} from '../lib/research/occlusion.mjs';
export default function LiveExplanation({explanation:e,selectedRegion,onSelect}:{explanation:any;selectedRegion:number;onSelect:(n:number)=>void}){
 const fusion=e.target==='MAO-B screening score',unit=fusion?'screening-score units':'pK units',digits=fusion?4:3,extent=fusion?1:10,selected=e.changes[selectedRegion],display=occlusionDisplay(selected.delta,fusion);
 const score=(n:number)=>n.toFixed(digits),signed=(n:number)=>(n>0?'+':'')+score(n);
 return <div className="explanation-view"><h3>Spatial occlusion</h3><p>Each region is masked in turn. Select a region to locate it on the structure and compare its scores.</p><div className="region-selector" aria-label="Spatial regions">{e.changes.map((r:any)=><button className="secondary" key={r.group} aria-pressed={selectedRegion===r.group} onClick={()=>onSelect(r.group)}>Region {regionLabel(r.group)}</button>)}</div>
 <div className="occlusion-comparison" aria-live="polite"><div><span>Original score</span><strong>{score(e.baseline)}</strong></div><div><span>Region {regionLabel(selectedRegion)} masked</span><strong>{score(selected.maskedScore??e.baseline-selected.delta)}</strong></div><div><span>Original − masked</span><strong>{display.negligible?'Below displayed precision':signed(selected.delta)}</strong></div></div>
 <p className="small">{display.negligible?'The change is smaller than '+display.threshold+' '+unit+'.':selected.delta>0?'Masking this region reduced the prediction.':'Masking this region increased the prediction.'}</p>
 <div className="occlusion-chart"><div className="chart-axis"><span>−{extent}</span><span>0</span><span>+{extent}</span></div>{e.changes.map((r:any)=>{const d=occlusionDisplay(r.delta,fusion),width=d.negligible?0:Math.min(50,Math.abs(r.delta)/extent*50);return <button key={r.group} className="occlusion-row" aria-pressed={selectedRegion===r.group} onClick={()=>onSelect(r.group)} aria-label={'Region '+regionLabel(r.group)+': '+(d.negligible?'change below displayed precision':signed(r.delta)+' '+unit)}><span>{regionLabel(r.group)}</span><span className="bar-track"><i className={r.delta<0?'negative':'positive'} style={{left:(r.delta<0?50-width:50)+'%',width:width+'%'}}/></span><span>{d.negligible?'below precision':signed(r.delta)}</span></button>;})}</div>
 <div className="occlusion-legend"><span><i/>Positive / right: masking lowers the score</span><span><i className="negative"/>Negative / left: masking raises the score</span></div>
 <p className="small">Fixed scale: ±{extent} {unit}. Solid bars show positive changes; hatched bars show negative changes. Geometry{fusion?' and SMILES':''} stays fixed.</p></div>;
}
