import {useEffect,useRef,useState} from 'react';
import {scopedViewer} from '../lib/research/viewer-lifecycle';
import {regionBounds,regionLabel,occlusionDisplay} from '../lib/research/occlusion.mjs';
import {camPlane,camSlice} from '../lib/research/grad-cam.mjs';
import {initialCamSelection,type CamSelection} from './GradCamExplanation';
type Props={molblock:string;proteinPdb?:string;explanation?:any;center?:number[];gridKind?:'fusion'|'gnina';selectedRegion?:number;highlightAtoms?:number[];camSelection?:CamSelection};
export default function ResearchMolecule({molblock,proteinPdb,explanation,center,gridKind='gnina',selectedRegion=0,highlightAtoms=[],camSelection=initialCamSelection}:Props){
 const occlusion=explanation?.method==='grouped-spatial-occlusion',cam=explanation?.method==='grad-cam';
 const slice=cam?camSlice(explanation,camSelection.axis,camSelection.index):undefined;
 const node=useRef<HTMLDivElement>(null),viewer=useRef<any>(null),ligand=useRef<any>(null),camFitted=useRef(false),occlusionFitted=useRef(false);const [error,setError]=useState(''),[ready,setReady]=useState(0);
 useEffect(()=>{let cancelled=false,dispose:(()=>void)|undefined;const container=node.current;camFitted.current=false;occlusionFitted.current=false;setError('');(async()=>{
  const mol=await import('3dmol');if(cancelled||!container)return;const scope=scopedViewer(()=>mol.createViewer(container,{backgroundColor:'#f5f7fb'})),v=scope.viewer;dispose=scope.dispose;viewer.current=v;
  if(proteinPdb){const protein=v.addModel(proteinPdb,'pdb');const chains=[...new Set(protein.selectedAtoms({}).map((a:any)=>a.chain))];chains.forEach((chain,i)=>protein.setStyle({chain},{cartoon:{color:i%2?'#9985bd':'#7594ca',opacity:.35}}));}
  ligand.current=v.addModel(molblock,'sdf');ligand.current.setStyle({not:{elem:'H'}},{stick:{radius:.14,colorscheme:'Jmol'},sphere:{scale:.23,colorscheme:'Jmol'}});
  if(proteinPdb){const atoms=ligand.current.selectedAtoms({}),pocket=v.getModel(0).selectedAtoms({}).filter((a:any)=>a.elem!=='H'&&atoms.some((b:any)=>(a.x-b.x)**2+(a.y-b.y)**2+(a.z-b.z)**2<25));v.getModel(0).setStyle({index:pocket.map((a:any)=>a.index)},{stick:{radius:.06,colorscheme:'Jmol'}},true);}
  v.zoomTo({model:proteinPdb?1:0});if(proteinPdb){v.zoom(.65);v.rotate(35,'z');v.rotate(25,'y');v.rotate(10,'x');}if(center&&!proteinPdb)v.zoom(.5);if(center)v.setSlab(-60,60);v.render();setReady(n=>n+1);
 })().catch(()=>{dispose?.();dispose=undefined;if(!cancelled)setError('The structure cannot be displayed on this device.');});return()=>{cancelled=true;dispose?.();viewer.current=null;ligand.current=null;container?.replaceChildren();};},[molblock,proteinPdb]);
 useEffect(()=>{const v=viewer.current,l=ligand.current;if(!v||!l)return;v.removeAllShapes();v.removeAllLabels();l.setStyle({not:{elem:'H'}},{stick:{radius:.14,colorscheme:'Jmol'},sphere:{scale:.23,colorscheme:'Jmol'}});
  if(highlightAtoms.length){l.setStyle({index:highlightAtoms},{sphere:{scale:.4,color:'#7594ca',opacity:.35}},true);const atoms=highlightAtoms.map(i=>l.selectedAtoms({index:i})[0]).filter(Boolean);for(let i=0;i<atoms.length;i++){const a=atoms[i];v.addLabel(String(highlightAtoms[i]+1),{position:a,fontSize:14,fontColor:'#191919',backgroundColor:'#ffffff',backgroundOpacity:.9});if(i)v.addLine({start:atoms[i-1],end:a,color:'#345da8',linewidth:3});}}
  if(center){const bounds=occlusion?regionBounds(selectedRegion,center,gridKind):{min:center.map(c=>c+(gridKind==='fusion'?-10:-12)),max:center.map(c=>c+(gridKind==='fusion'?14:12))};const color=occlusion?occlusionDisplay(explanation.changes[selectedRegion].delta,gridKind==='fusion').color:'#888888';const [x,y,z]=bounds.min;v.addBox({corner:{x,y,z},dimensions:{w:bounds.max[0]-x,h:bounds.max[1]-y,d:bounds.max[2]-z},color,wireframe:true,opacity:.7});
   if(occlusion){v.addBox({corner:{x,y,z},dimensions:{w:12,h:12,d:12},color,opacity:.055});const corners=Array.from({length:8},(_,i)=>({x:bounds.min[0]+((i>>2)&1)*12,y:bounds.min[1]+((i>>1)&1)*12,z:bounds.min[2]+(i&1)*12}));for(let i=0;i<8;i++)for(const bit of [1,2,4])if(!(i&bit))v.addCylinder({start:corners[i],end:corners[i|bit],radius:.10,color,opacity:.85});}}
  if(cam&&camSelection.overlay){v.addCustom(camPlane(explanation,camSelection.axis,camSelection.index));const s=camSlice(explanation,camSelection.axis,camSelection.index),corners=[s.cells[0],s.cells[11],s.cells[143],s.cells[132]].map((cell,i)=>{const p=cell.position.slice();p[s.u]+=[-1,1,1,-1][i];p[s.v]+=[-1,-1,1,1][i];return {x:p[0],y:p[1],z:p[2]};});for(let i=0;i<4;i++)v.addLine({start:corners[i],end:corners[(i+1)%4],color:'#345da8',linewidth:2});}
  if(!occlusion)occlusionFitted.current=false;if(occlusion&&!occlusionFitted.current){v.zoom(.6);occlusionFitted.current=true;}
  if(cam&&!camFitted.current){v.zoomTo();v.rotate(20,'y');v.rotate(12,'x');camFitted.current=true;}
  v.render();
 },[ready,highlightAtoms.join(','),selectedRegion,explanation,center,gridKind,camSelection.axis,camSelection.index,camSelection.overlay]);
 const caption=occlusion?'Outlined region '+regionLabel(selectedRegion):cam?(camSelection.overlay?'Grad-CAM slice: ':'Slice overlay hidden · ')+camSelection.axis.toUpperCase()+' = '+slice!.position.toFixed(2)+' Å':proteinPdb?'Ligand, binding pocket and protein ribbon':'Drag to rotate · scroll to zoom';
 return <div className={'molecule-panel'+(proteinPdb?' complex-view':'')}><div className="mol-view" ref={node} role="img" aria-label={'Three-dimensional '+(proteinPdb?'protein–ligand complex':'molecule')+'; '+caption+'. Drag to rotate.'}/>{error&&<p className="small" role="status">{error}</p>}<div className="viewer-caption"><span>{caption}</span><button className="secondary" onClick={()=>{if(cam){viewer.current?.zoomTo();viewer.current?.render();return;}viewer.current?.zoomTo({model:proteinPdb?1:0});if(proteinPdb)viewer.current?.zoom(occlusion?.39:.65);if(center&&!proteinPdb)viewer.current?.zoom(.5);if(center)viewer.current?.setSlab(-60,60);viewer.current?.render();}}>Reset view</button></div></div>;
}
