const {chromium}=require('C:/Users/Mick/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict'),os=require('node:os'),path=require('node:path');
const engine=process.env.TEST_BROWSER||'chrome',prefix=(process.env.QA_OUTPUT_DIR||'artifacts')+'/rethink-'+engine,root=(process.env.TEST_BASE_URL||'http://127.0.0.1:4322'+require('../deployment.config.mjs').siteBase).replace(/\/$/,'');
(async()=>{
 const profilesRoot=path.resolve(process.env.QA_OUTPUT_DIR||'.qa');fs.mkdirSync(profilesRoot,{recursive:true});const profile=fs.mkdtempSync(path.join(profilesRoot,'editorial-'+engine+'-'));
 const context=await chromium.launchPersistentContext(profile,{executablePath:engine==='edge'?'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe':'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-unsafe-swiftshader'],viewport:{width:1500,height:1000}}),browser=context.browser(),page=await context.newPage(),errors=[],checks=[],timings=[],fusionRecords=[],affinityRecords=[];
 page.setDefaultTimeout(120000);page.on('pageerror',e=>{errors.push(e.message);console.log('Browser error:',e.message);});
 const note=s=>{checks.push(s);console.log(s);};
 await context.addInitScript(()=>{window.__scientificMessages=[];const WorkerOriginal=window.Worker;window.Worker=class extends WorkerOriginal{constructor(...args){super(...args);this.addEventListener('message',e=>{if(['result','explanation','error'].includes(e.data.type))window.__scientificMessages.push(e.data);});}};});
 async function run(label){await page.evaluate(()=>window.__scientificMessages=[]);const start=Date.now();await page.getByRole('button',{name:label,exact:false}).click();await page.waitForFunction(()=>window.__scientificMessages.some(m=>['result','error'].includes(m.type)),null,{timeout:240000});assert.equal(await page.getByRole('alert').count(),0,await page.locator('.bench-output').innerText());timings.push({label,ms:Date.now()-start});return page.evaluate(()=>{const r=window.__scientificMessages.find(m=>m.type==='result').result;return JSON.parse(JSON.stringify(r,(_,v)=>typeof v==='bigint'?v.toString():ArrayBuffer.isView(v)?Array.from(v):v));});}
 async function explain(label='Evaluate spatial occlusion'){await page.evaluate(()=>window.__scientificMessages=[]);await page.getByRole('button',{name:label}).click();await page.waitForFunction(()=>window.__scientificMessages.some(m=>m.type==='explanation'||m.type==='error'),null,{timeout:120000});assert.equal(await page.getByRole('alert').count(),0,await page.locator('.bench-output').innerText());return page.evaluate(()=>{const e=window.__scientificMessages.find(m=>m.type==='explanation').result;return {...e,values:Array.from(e.values)};});}
 async function handoff(before){
  const url=page.url();
  assert.equal(await page.getByRole('button',{name:'Explain this prediction'}).count(),0);
  assert.equal(await page.getByRole('button',{name:before.modelId==='fusion-aofb'?'Calculate Grad-CAM':'Evaluate spatial occlusion',exact:true}).count(),1);
  assert.equal(await page.evaluate(()=>sessionStorage.getItem('research-prediction-handoff')),null);
  assert.equal(page.url(),url);return before;
 }
 async function ready3d(){await page.locator('.mol-view canvas').first().waitFor();await page.waitForTimeout(250);}
 try{
 await page.goto(root,{waitUntil:'networkidle'});assert.match(await page.title(),/^Protein–Ligand Binding Affinity Prediction/);assert.equal(await page.locator('.site-header nav a').count(),1);assert.equal(await page.locator('.project-scope a[href*="ugc.edu.hk"]').count(),0);assert.equal(await page.locator('.topic-row').count(),3);assert.deepEqual(await page.locator('.site-header nav a').allTextContents(),['Research team ↗']);assert.equal(await page.locator('.wordmark,.chapter-number,.section-label,.empty-number').count(),0);assert.equal(await page.locator('a[href="https://zzulc.github.io/DebbyCV/members.html"]').count(),1);assert.equal(await page.locator('.topic-row figcaption a[href^="https://doi.org/"]').count(),3);await page.screenshot({path:prefix+'-home.png',fullPage:true});
 const figure=page.getByRole('button',{name:'Enlarge Molecular representations'});await figure.focus();await page.keyboard.press('Enter');assert.equal(await page.locator('dialog[open]').count(),1);assert.equal(await page.locator('dialog[open] a[href^="https://doi.org/"]').count(),1);await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await figure.evaluate(e=>e===document.activeElement),true);note('Grant identity, three topics, plain funding acknowledgment and keyboard figure enlargement');
 await page.goto(root+'/topics/representing-molecules/#experiment',{waitUntil:'networkidle'});let r=await run('Generate representations');assert.equal(r.formula,'C2H6O');assert.equal(r.graph.positions.length,r.graph.atoms.length);await ready3d();await page.getByRole('button',{name:'Aspirin',exact:true}).click();r=await run('Generate representations');await page.getByRole('button',{name:'Torsion angles',exact:true}).click();await page.locator('#geometry-feature').selectOption('1');let selection=await page.locator('.geometry-measurement').getAttribute('data-atoms');assert.equal(selection,r.torsions[1].indices.join(','));assert.match(await page.locator('.geometry-measurement').innerText(),new RegExp(r.torsions[1].degrees.toFixed(2).replace('.','\\.')));assert.deepEqual(await page.locator('.molecular-graph [data-selected=true]').evaluateAll(es=>es.map(e=>Number(e.dataset.atomIndex)).sort((a,b)=>a-b)),[...r.torsions[1].indices].sort((a,b)=>a-b));await ready3d();await page.locator('.workbench').screenshot({path:prefix+'-representations.png'});note('Examples generate linked structures, graph, fingerprints, grid and correct torsion/atom selections');
 await page.getByRole('button',{name:'Caffeine',exact:true}).click();r=await run('Generate representations');assert.equal(r.formula,'C8H10N4O2');await page.locator('.custom-input summary').click();for(const s of ['invalid','CCO.CN','C'.repeat(101)]){await page.locator('#molecule-smiles').fill(s);await page.getByRole('button',{name:'Generate representations'}).click();await page.getByRole('alert').waitFor();assert.equal(await page.locator('.result-title').count(),0);}await page.locator('#molecule-smiles').fill('C[C@H](O)Cl');r=await run('Generate representations');assert.equal(r.smiles,'C[C@H](O)Cl');note('Caffeine and custom stereochemistry execute; invalid, disconnected and overlength inputs reject');
 await page.goto(root+'/topics/binding-affinity/#experiment',{waitUntil:'networkidle'});await ready3d();assert.equal(await page.locator('input[type=file],textarea').count(),0);assert.equal(await page.locator('.result-title').count(),0);await page.locator('.workbench').screenshot({path:prefix+'-affinity-preview.png'});
 const native=JSON.parse(fs.readFileSync('artifacts/gnina-native-occlusion.json','utf8'));
 for(const id of ['1hsg','1hvr']){await page.goto(root+'/topics/binding-affinity/#experiment',{waitUntil:'networkidle'});await page.getByRole('button',{name:id.toUpperCase()+' /'}).click();await page.getByRole('button',{name:'Calculate affinity'}).waitFor();r=await run('Calculate affinity');assert.equal(r.exampleId,id);assert.equal(r.gridSha256,native[id].gridSha256);assert.ok(Math.abs(r.outputs[0].value-native[id].baseline)<=.01);await handoff(r);const e=await explain();assert.equal(e.changes.length,8);assert.equal(e.inputIdentity,r.inputIdentity);for(let i=0;i<8;i++)assert.ok(Math.abs(e.changes[i].delta-native[id].changes[i])<1e-4);affinityRecords.push({id,result:r,explanation:e});await page.getByRole('button',{name:'Region H',exact:true}).click();assert.match(await page.locator('.viewer-caption').innerText(),/Outlined region H/);assert.equal(await page.getByRole('button',{name:'Region H',exact:true}).getAttribute('aria-pressed'),'true');await ready3d();await page.locator('.workbench').screenshot({path:prefix+'-'+id+'-occlusion.png'});note(id.toUpperCase()+': live native-grid affinity, pose score and all eight occlusions pass native parity');}
 await page.getByRole('button',{name:'Calculate affinity'}).click();await page.getByRole('button',{name:'Cancel calculation'}).click();assert.equal(await page.locator('.result-title').count(),0);await run('Calculate affinity');await page.getByRole('button',{name:'Evaluate spatial occlusion'}).click();await page.getByRole('button',{name:'1HSG /'}).click();assert.equal(await page.locator('.explanation-view').count(),0);r=await run('Calculate affinity');assert.equal(r.exampleId,'1hsg');note('Cancellation and changing complexes dispose calculations and suppress stale results');
 await page.goto(root+'/topics/screening-molecules/#experiment',{waitUntil:'networkidle'});assert.match(await page.locator('.download-notice').innerText(),/901 MB/);assert.equal(await page.getByRole('button',{name:'Evaluate spatial occlusion'}).count(),0);
 await page.locator('.custom-input summary').click();await page.locator('#molecule-smiles').fill('CCCO');const started=Date.now();r=await run('Calculate screening score');assert.deepEqual(r.explanationCapabilities,['grad-cam']);await handoff(r);const scoreText=await page.locator('.result-stats').innerText();const camWeightRequests=[];page.on('request',req=>{if(req.url().includes('/fusion-aofb/weights/'))camWeightRequests.push(req.url());});
 const e=await explain('Calculate Grad-CAM');assert.equal(r.modelId,'fusion-aofb');assert.equal(e.tokensSha256,r.tokensSha256);assert.equal(e.gridSha256,r.gridSha256);assert.equal(e.checkpointSha256,r.checkpointSha256);assert.equal(e.inputIdentity,r.inputIdentity);assert.deepEqual(e.spatialFrame.origin,r.center.map(c=>c-9.5));assert.equal(await page.locator('.result-stats').innerText(),scoreText);const fwd=JSON.parse(fs.readFileSync('public/research/fusion-aofb/manifest.json')),derivative=JSON.parse(fs.readFileSync('public/research/fusion-aofb/gradients-manifest.json')),extra=derivative.externalData.filter(x=>!fwd.externalData.some(y=>y.artifact.sha256===x.artifact.sha256));assert.deepEqual(camWeightRequests.map(u=>new URL(u).pathname),extra.map(x=>new URL(x.artifact.path,root+'/').pathname));assert.match(await page.locator('.explanation-download').innerText(),/0.57 MB/);fusionRecords.push({input:{smiles:'CCCO'},result:r,explanation:e});
 await ready3d();await page.locator('.workbench').screenshot({path:prefix+'-fusion-grad-cam.png'});note('Full Fusion prediction and live Grad-CAM preserve score and all input identities; derivative graph reuses cached weights ('+(Date.now()-started)+' ms)');
 for(const axis of ['x','y','z']){await page.getByLabel('Grad-CAM axis',{exact:true}).selectOption(axis);await page.getByLabel('Grad-CAM slice',{exact:true}).fill('0');await page.getByLabel('Grad-CAM slice',{exact:true}).press('ArrowRight');const index=1,ai=['x','y','z'].indexOf(axis),coordinate=e.spatialFrame.origin[ai]+2*index;assert.match(await page.locator('.viewer-caption').innerText(),new RegExp(axis.toUpperCase()+' = '+coordinate.toFixed(2)+' Å'));const rects=await page.locator('.cam-map rect').evaluateAll(es=>es.map(el=>({xyz:el.dataset.voxel.split(',').map(Number),value:Number(el.dataset.value),fill:el.getAttribute('fill')})));assert.equal(rects.length,144);for(const c of rects){assert.equal(c.xyz[ai],index);assert.equal(c.value,e.values[c.xyz[0]*144+c.xyz[1]*12+c.xyz[2]]);}await page.locator('.workbench').screenshot({path:prefix+'-cam-axis-'+axis+'.png'});}
 await page.getByLabel('Show slice on molecule').uncheck();assert.match(await page.locator('.viewer-caption').innerText(),/overlay hidden/);await page.getByLabel('Show slice on molecule').check();note('All three axes, keyboard slice controls, exact tensor values and overlay visibility remain linked');
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.locator('.workbench').screenshot({path:prefix+'-mobile-grad-cam.png'});await page.setViewportSize({width:1500,height:1000});
 await page.getByRole('button',{name:'Aspirin',exact:true}).click();r=await run('Calculate screening score');const negligible=await explain('Calculate Grad-CAM');assert.ok(negligible.values.every(x=>x<1e-8));assert.match(await page.locator('.cam-signal').innerText(),/Below colour-scale resolution/);assert.ok((await page.locator('.cam-map rect').evaluateAll(es=>es.map(el=>el.getAttribute('fill')))).every(c=>c==='#f2f2f2'));fusionRecords.push({input:{smiles:'CC(=O)Oc1ccccc1C(=O)O'},result:r,explanation:negligible});await page.locator('.workbench').screenshot({path:prefix+'-cam-negligible.png'});note('Near-zero Grad-CAM stays neutral without per-molecule contrast amplification');
 await page.getByRole('button',{name:'Calculate Grad-CAM'}).click();await page.getByRole('button',{name:'Cancel calculation'}).click();assert.equal(await page.locator('.result-title').count(),0);await run('Calculate screening score');await page.getByRole('button',{name:'Calculate Grad-CAM'}).click();await page.getByRole('button',{name:'Ethanol',exact:true}).click();assert.equal(await page.locator('.explanation-view,.result-title').count(),0);r=await run('Calculate screening score');const ethanol=await explain('Calculate Grad-CAM');fusionRecords.push({input:{smiles:'CCO'},result:r,explanation:ethanol});note('Explanation cancellation and input changes dispose sessions and suppress stale results; cached restart works');
 await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded'});await page.locator('.custom-input summary').click();await page.locator('#molecule-smiles').fill('C[C@H](O)Cl');r=await run('Calculate screening score');const offline=await explain('Calculate Grad-CAM');fusionRecords.push({input:{smiles:'C[C@H](O)Cl'},result:r,explanation:offline});await page.goto(root+'/topics/binding-affinity/#experiment',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'1HVR /'}).click();r=await run('Calculate affinity');assert.deepEqual(r.explanationCapabilities,['grouped-spatial-occlusion']);assert.equal(r.exampleId,'1hvr');await handoff(r);await explain();await context.setOffline(false);note('Offline reload, new Fusion input with Grad-CAM, and affinity with occlusion execute from verified caches');
 await page.goto(root+'/topics/explainability/?method=grad-cam&from=prediction#experiment',{waitUntil:'networkidle'});await page.waitForURL('**/topics/screening-molecules/?method=grad-cam&from=prediction#experiment');await page.getByText('Your earlier prediction could not be verified',{exact:false}).waitFor();assert.equal(await page.locator('.result-title,.explanation-view').count(),0);
 await page.goto(root+'/demos/explainability/#occlusion');await page.waitForURL('**/topics/binding-affinity/#occlusion');note('Legacy methods redirect to their articles; missing snapshot offers a fresh calculation without unrelated results');
 await page.setViewportSize({width:390,height:844});for(const url of ['/', '/topics/representing-molecules/','/topics/screening-molecules/','/topics/binding-affinity/','/topics/explainability/']){await page.goto(root+url,{waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,url);await page.screenshot({path:prefix+'-mobile-'+(url==='/'?'home':url.split('/')[2])+'.png',fullPage:true});}note('Home and all topics fit mobile viewport without horizontal overflow');
 await page.goto(root+'/about/');await page.waitForURL(root+'/#topics');await page.goto(root+'/works/');await page.waitForURL(root+'/#topics');note('Retired pages redirect to the homepage');
 assert.deepEqual(errors,[]);fs.writeFileSync(prefix+'-fusion-outputs.json',JSON.stringify(fusionRecords));fs.writeFileSync(prefix+'-affinity-outputs.json',JSON.stringify(affinityRecords));fs.writeFileSync(prefix+'-verification.json',JSON.stringify({passed:true,date:new Date().toISOString(),browser:browser.version(),device:{cpu:os.cpus()[0].model,ram:os.totalmem()},checks,errors,timings},null,2));
 }finally{await context.close();if(path.dirname(profile)!==profilesRoot||!path.basename(profile).startsWith('editorial-'+engine+'-'))throw Error('Unexpected temporary test profile path');fs.rmSync(profile,{recursive:true,force:true,maxRetries:5,retryDelay:300});}
})().catch(e=>{console.error(e);process.exit(1)});
